/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    ADatePicker: typeof import('@arco-design/web-vue')['DatePicker']
    ADescriptions: typeof import('@arco-design/web-vue')['Descriptions']
    ADescriptionsItem: typeof import('@arco-design/web-vue')['DescriptionsItem']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    APopconfirm: typeof import('@arco-design/web-vue')['Popconfirm']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    ARangePicker: typeof import('@arco-design/web-vue')['RangePicker']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    ATextarea: typeof import('@arco-design/web-vue')['Textarea']
    ATrigger: typeof import('@arco-design/web-vue')['Trigger']
    DarkToggle: typeof import('./components/DarkToggle.vue')['default']
    MRange: typeof import('vue-range-multi')['Range']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAchievementModal: typeof import('./components/TheAchievementModal.vue')['default']
    TheFeedback: typeof import('./components/TheFeedback.vue')['default']
    TheGoalContent: typeof import('./components/TheGoalContent.vue')['default']
    TheGoalDetail: typeof import('./components/TheGoalDetail.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheIconSelector: typeof import('./components/TheIconSelector.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheNav: typeof import('./components/TheNav.vue')['default']
    TheProgress: typeof import('./components/TheProgress.vue')['default']
    TheRecordCard: typeof import('./components/TheRecordCard.vue')['default']
    TheRecordDrawer: typeof import('./components/TheRecordDrawer.vue')['default']
    TheRender: typeof import('./components/TheRender.vue')['default']
  }
}
